<?php

namespace Database\Factories;

use App\Models\City;
use App\Models\SavedSearch;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<SavedSearch>
 */
class SavedSearchFactory extends Factory
{
    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'city_id' => City::factory(),
            'locale' => 'en',
            'name' => 'My search',
            'title' => 'My search',
            'description' => null,
            'status' => 'active',
            'city' => $this->faker->city(),
            'district' => null,
            'location_text' => null,
            'radius_meters' => null,
            'check_in' => now()->addWeek()->toDateString(),
            'check_out' => now()->addDays(10)->toDateString(),
            'check_in_date' => now()->addWeek()->toDateString(),
            'check_out_date' => now()->addDays(10)->toDateString(),
            'flexible_dates' => false,
            'flexible_days' => null,
            'nights' => 3,
            'nights_count' => 3,
            'calendar_days_count' => 4,
            'guests_count' => 1,
            'price_min' => 10,
            'price_max' => 50,
            'budget_min' => 10,
            'budget_max' => 50,
            'total_budget_max' => null,
            'currency' => 'EUR',
            'room_type' => 'shared',
            'bed_type' => 'single',
            'amenities' => ['wifi'],
            'filters' => ['quiet' => true],
            'filters_json' => ['quiet' => true],
            'property_types_json' => [],
            'room_types_json' => ['shared'],
            'sleeping_place_types_json' => ['single'],
            'room_gender_policy' => null,
            'required_amenity_ids_json' => [],
            'preferred_amenity_ids_json' => [],
            'excluded_rule_ids_json' => [],
            'excluded_conditions_json' => [],
            'only_verified_hosts' => false,
            'only_verified_places' => false,
            'only_instant_booking' => false,
            'only_with_reviews' => false,
            'free_cancellation_only' => false,
            'no_deposit_only' => false,
            'max_deposit' => null,
            'min_rating' => null,
            'min_cleanliness_rating' => null,
            'min_safety_rating' => null,
            'min_host_rating' => null,
            'max_people_in_room' => null,
            'lower_bunk_only' => false,
            'exclude_upper_bunk' => false,
            'exclude_sofa' => false,
            'exclude_mattress' => false,
            'require_locker' => false,
            'require_workspace' => false,
            'require_wifi' => false,
            'require_kitchen' => false,
            'require_washing_machine' => false,
            'require_late_check_in' => false,
            'avoid_smoking' => false,
            'avoid_pets' => false,
            'avoid_mixed_room' => false,
            'notify_new_places' => true,
            'notify_price_drop' => false,
            'notify_available' => true,
            'notify_frequency' => 'daily',
            'notify_new_matches' => true,
            'notify_price_drops' => true,
            'notify_price_increases' => false,
            'notify_available_again' => true,
            'notify_better_match' => true,
            'notification_frequency' => 'on_visit',
            'quiet_hours_enabled' => true,
            'quiet_hours_start' => '22:00',
            'quiet_hours_end' => '07:00',
            'last_checked_at' => null,
            'last_notified_at' => null,
            'next_check_at' => null,
            'new_matches_count' => 0,
            'price_drops_count' => 0,
            'available_again_count' => 0,
            'last_results_hash' => null,
            'is_active' => true,
        ];
    }
}
